CREATE SEQUENCE SQ_CONTATO
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

CREATE TABLE TBL_CONTATO(
    CONTATO_ID INTEGER DEFAULT SQ_CONTATO.NEXTVAL NOT NULL,
    NOME VARCHAR2(100) NOT NULL,
    EMAIL VARCHAR2(100) NOT NULL,
    SENHA VARCHAR2(100) NOT NULL,
    data_nascimento DATE NOT NULL
);