CREATE SEQUENCE SQ_USUARIO
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

CREATE TABLE TBL_USUARIO(
    USUARIO_ID INTEGER DEFAULT SQ_USUARIO.NEXTVAL NOT NULL,
    USUARIO_NOME VARCHAR2(100) NOT NULL,
    USUARIO_EMAIL VARCHAR2(100) UNIQUE NOT NULL,
    USUARIO_SENHA VARCHAR2(100) NOT NULL,
    USUARIO_ROLE VARCHAR2(50) DEFAULT 'USER'
);